version: 2.1

executors:
  my-executor:
    docker:
      - image: circleci/node:10-browsers
    working_directory: ~/repo

jobs:
  build:
    executor: my-executor
    steps:
      - checkout
      - restore_cache:
          key: repo-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - save_cache:
          key: repo-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - 'node_modules'
      - run: npm install
      - run: npm run build
      - run:
          name: Publish to GitHub Packages
          command: |
            npm set //npm.pkg.github.com/:_authToken=${GITHUB_PACKAGE_PAT}
            npm publish
workflows:
  version: 2
  auto_package_workflow:
    jobs:
      - build
